swagger: '2.0'
info:
  title: Rent-A-Car API
  description: Example Typescrtipt backend application
  version: 1.0.0
host: racapp-ckibfdodrq-ue.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://racapp-ckibfdodrq-ue.a.run.app
  protocol: h2
paths:
  "/profile":
    get:
      operationId: AppController_getProfile
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/rental":
    post:
      operationId: RentalController_createRental
      parameters: []
      responses:
        '201':
          description: ''
    get:
      operationId: RentalController_searchRental
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/rental/edit-price":
    post:
      operationId: RentalController_editPricing
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/rental/edit-details":
    post:
      operationId: RentalController_editDetails
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/rental/schedule-unavailability":
    post:
      operationId: RentalController_scheduleUnavailability
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/rental/update-unavailability":
    post:
      operationId: RentalController_updateUnavailability
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/rental/remove-unavailability":
    post:
      operationId: RentalController_removeUnavailability
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/auth/login":
    post:
      operationId: AuthController_login
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/auth/logout":
    post:
      operationId: AuthController_logout
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/auth/change-password":
    post:
      operationId: AuthController_changePassword
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/auth/forgot-password":
    post:
      operationId: AuthController_forgotPassword
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/auth/reset-password":
    post:
      operationId: AuthController_resetPassword
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/user/create-user":
    post:
      operationId: UserController_createProfile
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/user/update-user":
    post:
      operationId: UserController_updateProfile
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/user/find-user":
    get:
      operationId: UserController_findUser
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/user/delete-profile":
    post:
      operationId: UserController_deleteProfile
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/images/upload-rental-images":
    post:
      operationId: ImagesController_uploadRentalImages
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/images/upload-profile-images":
    post:
      operationId: ImagesController_uploadProfileImage
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/images/find-rental-images":
    get:
      operationId: ImagesController_findRentalImages
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/images/find-rental-image":
    get:
      operationId: ImagesController_findRentalImage
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/images/find-profile-images":
    get:
      operationId: ImagesController_findProfileImages
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/images/find-profile-image":
    get:
      operationId: ImagesController_findProfileImage
      parameters: []
      responses:
        '200':
          description: ''
  "/v1/images/delete-images":
    post:
      operationId: ImagesController_deleteImages
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/images/delete-all-rental-images":
    post:
      operationId: ImagesController_deleteAllRentalImages
      parameters: []
      responses:
        '201':
          description: ''
  "/v1/images/delete-all-profile-images":
    post:
      operationId: ImagesController_deleteAllProfileImages
      parameters: []
      responses:
        '201':
          description: ''